name: /Users/hongxuzhou/MyT5Project/env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - filelock=3.20.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - jinja2=3.1.6
  - libcxx=20.1.8
  - libffi=3.4.4
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - markupsafe=3.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.5
  - openssl=3.0.18
  - pip=25.3
  - python=3.11.14
  - pyyaml=6.0.3
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - sympy=1.14.0
  - tk=8.6.15
  - typing_extensions=4.15.0
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - pip:
      - aiofiles==24.1.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - asttokens==3.0.1
      - bertviz==1.4.1
      - boto3==1.42.11
      - botocore==1.42.11
      - brotli==1.2.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - decorator==5.2.1
      - executing==2.2.1
      - fastapi==0.122.0
      - ffmpy==1.0.0
      - fsspec==2025.10.0
      - gradio==6.0.1
      - gradio-client==2.0.0
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jmespath==1.0.1
      - markdown-it-py==4.0.0
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - numpy==2.3.5
      - orjson==3.11.4
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - prompt-toolkit==3.0.52
      - protobuf==6.33.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - s3transfer==0.16.0
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.50.0
      - tokenizers==0.22.1
      - tomlkit==0.13.3
      - torch==2.8.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.3
      - typer==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - wcwidth==0.2.14
prefix: /Users/hongxuzhou/MyT5Project/env
